# -*- coding: utf-8 -*-
"""Detecção de Anomalias em Transações em Python-DIO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i-ugfCzAT1uirz8D_Ur8R2yw0ULZERQc
"""

# ============================================
# PROJETO DIO - DETECÇÃO DE ANOMALIAS
# 100% ONLINE - SEM INSTALAÇÃO
# ============================================

# 1. INSTALAR BIBLIOTECAS (somente essa linha)
!pip install -q imbalanced-learn xgboost shap

# 2. IMPORTAR BIBLIOTECAS
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix
from imblearn.over_sampling import SMOTE
import shap
import warnings
warnings.filterwarnings('ignore')

# 3. CRIAR DATASET SIMULADO (substitua pelo seu arquivo depois)
print("📊 CRIANDO DATASET DE TRANSAÇÕES...")
X, y = make_classification(
    n_samples=10000,
    n_features=20,
    n_informative=15,
    n_redundant=5,
    weights=[0.97, 0.03],  # 3% de fraudes
    random_state=42
)

# Criar DataFrame
df = pd.DataFrame(X, columns=[f'Feature_{i}' for i in range(X.shape[1])])
df['Class'] = y
print(f"✅ Dataset criado com {len(df)} transações")
print(f"📈 Distribuição:\n{df['Class'].value_counts()}")

# 4. ANÁLISE EXPLORATÓRIA
plt.figure(figsize=(12,5))

# Gráfico 1: Distribuição das classes
plt.subplot(1,2,1)
sns.countplot(x='Class', data=df)
plt.title('Distribuição das Transações\n(Normal vs Fraude)', fontsize=12)
plt.xlabel('Classe (0=Normal, 1=Fraude)')

# Gráfico 2: Matriz de Correlação (amostra)
plt.subplot(1,2,2)
corr = df.corr()['Class'].sort_values(ascending=False).head(10)
corr.drop('Class').plot(kind='bar', color=['green' if x < 0 else 'red' for x in corr.drop('Class')])
plt.title('Top 10 Features Correlacionadas com Fraude', fontsize=12)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 5. PRÉ-PROCESSAMENTO
print("\n🔄 PRÉ-PROCESSANDO DADOS...")
X = df.drop('Class', axis=1)
y = df['Class']

# Padronizar
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Dividir treino/teste
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.3, random_state=42, stratify=y
)
print(f"📊 Treino: {len(X_train)} | Teste: {len(X_test)}")

# 6. BALANCEAMENTO COM SMOTE
print("\n⚖️ APLICANDO SMOTE...")
print(f"Antes: {dict(zip(*np.unique(y_train, return_counts=True)))}")

smote = SMOTE(random_state=42)
X_train_balanced, y_train_balanced = smote.fit_resample(X_train, y_train)

print(f"Depois: {dict(zip(*np.unique(y_train_balanced, return_counts=True)))}")

# 7. TREINAR MODELOS
print("\n🤖 TREINANDO MODELOS...")

# Modelo 1: Random Forest
rf = RandomForestClassifier(n_estimators=50, max_depth=8, random_state=42)
rf.fit(X_train_balanced, y_train_balanced)
y_pred_rf = rf.predict(X_test)

# Modelo 2: XGBoost
xgb = XGBClassifier(n_estimators=50, max_depth=6, random_state=42, use_label_encoder=False, eval_metric='logloss')
xgb.fit(X_train_balanced, y_train_balanced)
y_pred_xgb = xgb.predict(X_test)

# 8. AVALIAÇÃO DOS RESULTADOS
print("\n" + "="*60)
print("📊 RESULTADOS DA AVALIAÇÃO")
print("="*60)

# Random Forest
print("\n🔵 RANDOM FOREST:")
print(classification_report(y_test, y_pred_rf, target_names=['Normal', 'Fraude']))
print(f"AUC-ROC: {roc_auc_score(y_test, y_pred_rf):.4f}")

# XGBoost
print("\n🟢 XGBOOST:")
print(classification_report(y_test, y_pred_xgb, target_names=['Normal', 'Fraude']))
print(f"AUC-ROC: {roc_auc_score(y_test, y_pred_xgb):.4f}")

# 9. MATRIZ DE CONFUSÃO
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

for idx, (model, name) in enumerate([(y_pred_rf, 'Random Forest'), (y_pred_xgb, 'XGBoost')]):
    cm = confusion_matrix(y_test, model)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[idx])
    axes[idx].set_title(f'Matriz de Confusão - {name}')
    axes[idx].set_xlabel('Previsto')
    axes[idx].set_ylabel('Real')
plt.tight_layout()
plt.show()

# 10. EXPLICABILIDADE COM SHAP
print("\n🔍 EXPLICANDO AS PREVISÕES COM SHAP...")

# Escolher XGBoost para explicar (melhor performance)
explainer = shap.TreeExplainer(xgb)
shap_values = explainer.shap_values(X_test[:100])  # Usar 100 amostras

# Gráfico de importância
plt.figure(figsize=(10,6))
shap.summary_plot(shap_values, X_test[:100], feature_names=[f'Feature_{i}' for i in range(X.shape[1])], show=False)
plt.title('Importância das Features (SHAP)', fontsize=14)
plt.tight_layout()
plt.show()

# 11. AJUSTE DE THRESHOLD
print("\n🎯 AJUSTANDO THRESHOLD PARA MELHORAR DETECÇÃO...")

y_proba = xgb.predict_proba(X_test)[:, 1]
thresholds = [0.3, 0.4, 0.5, 0.6]

for thresh in thresholds:
    y_pred_adj = (y_proba >= thresh).astype(int)
    auc = roc_auc_score(y_test, y_pred_adj)
    print(f"Threshold {thresh}: AUC = {auc:.4f}")

# Melhor threshold (você pode ajustar)
best_threshold = 0.4
y_pred_best = (y_proba >= best_threshold).astype(int)
print(f"\n✅ MELHOR THRESHOLD ENCONTRADO: {best_threshold}")
print(classification_report(y_test, y_pred_best, target_names=['Normal', 'Fraude']))

print("\n" + "="*60)
print("✅ PROJETO CONCLUÍDO COM SUCESSO!")
print("="*60)
print("\n💡 DICA: Para usar seus próprios dados, substitua a seção")
print("   de criação do dataset pelo upload do seu arquivo CSV:")
print("   from google.colab import files")
print("   uploaded = files.upload()")
print("   df = pd.read_csv('seu_arquivo.csv')")

